on: [push]

name: build

jobs:
  covr:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"    

    timeout-minutes: 10

    runs-on: ubuntu-latest

    name: build

    strategy:
      fail-fast: false

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/jammy/latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install bhgc.website
        run: |
          install.packages(".", repos = NULL)
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          capabilities()
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Build
        run: |
          bhgc.website::build()
        shell: Rscript {0}

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout gh-pages
          git add -f html
          git commit -am "bhgc.website::build()"
          git push

      - name: Upload build results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-build-results
          path: check
    
